### PR TITLE
Fix for "Attempting re-set scenario ID for unfinished scenario"

### PR DESCRIPTION
**Pull request by evgenytkachenko**
Fix for https://github.com/reportportal/agent-java-cucumber4/issues/8

### CODE REVIEW

**Comment by evgenytkachenko** [comment]
@DzmitryHumianiuk can someone take a look at this?
1 line of code but it helps a lot

**Comment by evgenytkachenko** [comment]
@DzmitryHumianiuk thanks 
Will we have a version 4.2.0 of this agent soon?

**Comment by DzmitryHumianiuk** [comment]
@evgenytkachenko 
@HardNorth is on that. I guess, newest version will be release along with 5.0 adoptation

**Comment by evgenytkachenko** [comment]
Thanks

**Comment by amar-1314** [comment]
any update on this?

**Comment by evgenytkachenko** [comment]
@amar-1314 can you try to use 4.1.1 version ?
does it fix an issue for you ?

**Comment by amar-1314** [comment]
@evgenytkachenko I got a reply on slack saying v4 doesnt support parallel run so i upgraded to v5 and it runs with no issues.

**Pull request merged**
